---
- name: Configure Debian host
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: Tailscale repository key
      ansible.builtin.apt_key:
        url: https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg
        state: present

    - name: Tailscale repository
      ansible.builtin.apt_repository:
        repo: "deb https://pkgs.tailscale.com/stable/debian {{ ansible_distribution_release }} main"
        state: present
        filename: tailscale
        update_cache: true

    - name: Install packages
      ansible.builtin.apt:
        name:
          - sudo
          - ufw
          - tailscale
          - vi
          - mc
          - btop
          - git
          - curl
          - wget
          - powertop
          - smartmontools
          - bash_completion
          - fastfetch
        state: present
        update_cache: true
