---
- name: Configure Debian host
  hosts: all
  remote_user: root
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - sudo
          - gpg
          - ufw
          - vim
          - mc
          - btop
          - git
          - curl
          - wget
          - powertop
          - smartmontools
          - bash-completion
          - fastfetch
        state: present
        update_cache: true

    - name: Download Tailscale GPG key
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
        mode: '0644'

    - name: Tailscale repository
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/debian/trixie.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list
        mode: '0644'

    - name: Install Tailscale
      ansible.builtin.apt:
        name: tailscale
        state: present
        update_cache: true
