---
- name: Create user
  hosts: all
  remote_user: root

  tasks:
    - name: Create user
      ansible.builtin.user:
        name: '{{ username }}'
        password: '$6$BihGRY4qdpQuOelt$5IfJpfOUkL6v8nMCvPxr.zCvoxvZ1fKjuhZ3SiFyXAwGnyzX6g5E6IpunVbYz4SlP2yTIHK1RB.Nr0hN5qUBj0'
        state: present
        create_home: true
        shell: /bin/bash
        generate_ssh_key: true

    - name: Add authorized key
      ansible.posix.authorized_key:
        user: '{{ username }}'
        state: present
        key: 'file://~/.ssh/id_rsa.pub'

    - name: Add user to sudoers.d
      ansible.builtin.lineinfile:
        path: '/etc/sudoers.d/{{ username }}'
        create: true
        regexp: '^{{ username }} ALL='
        line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
        mode: '0644'
