---
- name: Configure user environment
  hosts: localhost
  connection: local
  vars:
    prompt_time: '\[$(tput setaf 240)\]\t \[$(tput setaf 15)\]'
    prompt_chroot: '${debian_chroot:+($debian_chroot)}'
    prompt_presets:
      green: '\[$(tput setaf 40)\]\u@\h\[$(tput sgr0)\]:\[$(tput setaf 33)\]\w\[$(tput sgr0)\]\$ '
      red: '\[$(tput setaf 9)\]\u@\h\[$(tput sgr0)\]:\[$(tput setaf 33)\]\w\[$(tput sgr0)\]\$ '
      pink: '\[$(tput setaf 213)\]\u@\h\[$(tput sgr0)\]:\[$(tput setaf 33)\]\w\[$(tput sgr0)\]\$ '
      magenta: '\[$(tput setaf 201)\]\u@\h\[$(tput sgr0)\]:\[$(tput setaf 33)\]\w\[$(tput sgr0)\]\$ '
      orange: '\[$(tput setaf 208)\]\u@\h\[$(tput sgr0)\]:\[$(tput setaf 33)\]\w\[$(tput sgr0)\]\$ '
      yellow: '\[$(tput setaf 226)\]\u@\h\[$(tput sgr0)\]:\[$(tput setaf 33)\]\w\[$(tput sgr0)\]\$ '
    prompt_preset: "{{ prompt_presets[prompt | default('green')] }}"

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        dest: "{{ ansible_user_dir }}/.ssh"
        state: directory
        mode: '0700'

    - name: Generate SSH keys
      community.crypto.openssh_keypair:
        type: ed25519
        path: "{{ ansible_user_dir }}/.ssh/id_ed25519"
        comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
        mode: '0600'

    - name: Force color prompt
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        create: true
        mode: '0644'
        regexp: '^#force_color_prompt='
        line: 'force_color_prompt=yes'

    - name: Bashrc includes directory
      ansible.builtin.file:
        dest: "{{ ansible_user_dir }}/.bashrc.d"
        state: directory
        mode: '0755'

    - name: Source bashrc.d in .bashrc
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        create: true
        mode: '0644'
        marker: "# {mark} bashrc.d"
        block: |
          if [ -d "$HOME/.bashrc.d" ]; then
              for file in "$HOME/.bashrc.d"/*; do
                  if [ -f "$file" ]; then
                      . "$file"
                  fi
              done
          fi

    - name: Cd aliases
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc.d/cd"
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^alias \.\.=', line: 'alias ..="cd .."' }
        - { regexp: '^alias \.\.\.=', line: 'alias ...="cd ../.."' }
        - { regexp: '^alias ~=', line: 'alias ~="cd ~"' }
        - { regexp: '^alias --', line: 'alias -- --="cd --"' }

    - name: Ls aliases
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc.d/ls"
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^alias ls=', line: 'alias ls="ls --color=auto"' }
        - { regexp: '^alias l=', line: 'alias l="ls -lF --si"' }
        - { regexp: '^alias ll=', line: 'alias ll="ls -laF --si"' }

    - name: Grep aliases
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc.d/grep"
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^alias grep=', line: 'alias grep="grep --color=auto"' }
        - { regexp: '^alias egrep=', line: 'alias egrep="egrep --color=auto"' }
        - { regexp: '^alias fgrep=', line: 'alias fgrep="fgrep --color=auto"' }

    - name: Docker compose aliases
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc.d/docker"
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^alias dcu=', line: 'alias dcu="docker compose up -d"' }
        - { regexp: '^alias dcd=', line: 'alias dcd="docker compose down"' }
        - { regexp: '^alias dcr=', line: 'alias dcr="docker compose restart"' }
        - { regexp: '^alias dcl=', line: 'alias dcl="docker logs --follow --tail=100"' }
        - { regexp: '^alias vdc=', line: 'alias vdc="vi docker-compose.yml"' }

    - name: Bash search hotkeys
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.inputrc"
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^"\\e\[A":', line: '"\e\[A": history-search-backward' }
        - { regexp: '^"\\e\[B":', line: '"\e\[B": history-search-forward' }
        - { regexp: '^set completion-ignore-case', line: 'set completion-ignore-case on' }

    - name: Prompt color
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.bashrc"
        create: true
        mode: '0644'
        regexp: '^\s*PS1='
        insertafter: '^if \[ "\$color_prompt" = yes \]; then'
        firstmatch: true
        line: "  PS1='{{ prompt_time }}{{ prompt_chroot }}{{ prompt_preset }}'"

    - name: Editor
      ansible.builtin.lineinfile:
        path: "{{ ansible_user_dir }}/.profile"
        create: true
        mode: '0644'
        regexp: '^export EDITOR='
        line: 'export EDITOR=/usr/bin/vi'

    - name: Fastfetch call in .motd
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.motd"
        create: true
        mode: '0644'
        marker: "# {mark} fastfetch"
        block: |
          echo -e ""
          fastfetch
          echo -e ""

    - name: Config directory
      ansible.builtin.file:
        dest: "{{ ansible_user_dir }}/.config"
        state: directory
        mode: '0755'

    - name: Fastfetch config directory
      ansible.builtin.file:
        dest: "{{ ansible_user_dir }}/.config/fastfetch"
        state: directory
        mode: '0755'

    - name: Fastfetch config
      ansible.builtin.copy:
        src: files/fastfetch.jsonc
        dest: "{{ ansible_user_dir }}/.config/fastfetch/config.jsonc"
        mode: '0644'

    - name: .motd call
      ansible.builtin.blockinfile:
        path: "{{ ansible_user_dir }}/.profile"
        create: true
        mode: '0644'
        marker: "# {mark} motd"
        block: |
          if [ -f "$HOME/.motd" ]; then
              . "$HOME/.motd"
          fi

    - name: Midnight Commander config directory
      ansible.builtin.file:
        dest: "{{ ansible_user_dir }}/.config/mc"
        state: directory
        mode: '0755'

    - name: Midnight Commander ini file
      ansible.builtin.copy:
        src: files/mc.ini
        dest: "{{ ansible_user_dir }}/.config/mc/ini"
        mode: '0644'

    - name: Git config user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: "Alexey Donov"

    - name: Git config user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: "alexeydonov@mac.com"
