---
- name: Configure user environment
  hosts: localhost
  connection: local

  tasks:
    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        dest: /home/{{ ansible_user_id }}/.ssh
        state: directory
        mode: '0700'

    - name: Generate SSH keys
      community.crypto.openssh_keypair:
        type: ed25519
        path: /home/{{ ansible_user_id }}/.ssh/id_ed25519
        comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
        mode: '0600'

    - name: Force color prompt
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.bashrc
        create: true
        mode: '0644'
        regexp: '^#force_color_prompt='
        line: 'force_color_prompt=yes'

    - name: Bashrc includes directory
      ansible.builtin.file:
        dest: /home/{{ ansible_user_id }}/.bashrc.d
        state: directory
        mode: '0755'

    - name: Source bashrc.d in .bashrc
      ansible.builtin.blockinfile:
        path: /home/{{ ansible_user_id }}/.bashrc
        create: true
        mode: '0644'
        marker: "# {mark} bashrc.d"
        block: |
          if [ -d "$HOME/.bashrc.d" ]; then
              for file in "$HOME/.bashrc.d"/*; do
                  if [ -f "$file" ]; then
                      . "$file"
                  fi
              done
          fi

    - name: Cd aliases
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.bashrc.d/cd
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^alias cd\.\.=', line: 'alias cd..="cd .."' }
        - { regexp: '^alias cd\.\.\.=', line: 'alias cd...="cd ../.."' }

    - name: Ls aliases
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.bashrc.d/ls
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^alias ls=', line: 'alias ls="ls --color=auto"' }
        - { regexp: '^alias l=', line: 'alias l="ls -lF --si"' }
        - { regexp: '^alias ll=', line: 'alias ll="ls -laF --si"' }

    - name: Grep aliases
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.bashrc.d/grep
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^alias grep=', line: 'alias grep="grep --color=auto"' }
        - { regexp: '^alias egrep=', line: 'alias egrep="egrep --color=auto"' }
        - { regexp: '^alias fgrep=', line: 'alias fgrep="fgrep --color=auto"' }

    - name: Bash search hotkeys
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.inputrc
        create: true
        mode: '0644'
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - { regexp: '^"\\e\[A":', line: '"\e\[A": history-search-backward' }
        - { regexp: '^"\\e\[B":', line: '"\e\[B": history-search-forward' }
        - { regexp: '^set completion-ignore-case', line: 'set completion-ignore-case on' }

    - name: Editor
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.profile
        create: true
        mode: '0644'
        regexp: '^export EDITOR='
        line: 'export EDITOR=/usr/bin/vi'

    - name: Fastfetch call in .motd
      ansible.builtin.blockinfile:
        path: /home/{{ ansible_user_id }}/.motd
        create: true
        mode: '0744'
        marker: "# {mark} fastfetch"
        block: |
          echo -e ""
          fastfetch
          echo -e ""

    - name: Config directory
      ansible.builtin.file:
        dest: /home/{{ ansible_user_id }}/.config
        state: directory
        mode: '0755'

    - name: Fastfetch config directory
      ansible.builtin.file:
        dest: /home/{{ ansible_user_id }}/.config/fastfetch
        state: directory
        mode: '0755'

    - name: Fastfetch config
      ansible.builtin.copy:
        src: files/fastfetch.jsonc
        dest: /home/{{ ansible_user_id }}/.config/fastfetch/config.jsonc
        mode: '0644'

    - name: .motd call
      ansible.builtin.blockinfile:
        path: /home/{{ ansible_user_id }}/.profile
        create: true
        mode: '0644'
        marker: "# {mark} motd"
        block: |
          if [ -f "$HOME/.motd" ]; then
              . "$HOME/.motd"
          fi

    - name: Midnight Commander config directory
      ansible.builtin.file:
        dest: /home/{{ ansible_user_id }}/.config/mc
        state: directory
        mode: '0755'

    - name: Midnight Commander keymap panel section
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.config/mc/mc.keymap
        create: true
        mode: '0644'
        regexp: '^\[panel\]$'
        line: '[panel]'

    - name: Midnight Commander keymap CdChild
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.config/mc/mc.keymap
        create: true
        mode: '0644'
        regexp: '^CdChild ='
        line: 'CdChild = right'
        insertafter: '^\[panel\]$'

    - name: Midnight Commander keymap CdParent
      ansible.builtin.lineinfile:
        path: /home/{{ ansible_user_id }}/.config/mc/mc.keymap
        create: true
        mode: '0644'
        regexp: '^CdParent ='
        line: 'CdParent = left'
        insertafter: '^\[panel\]$'

    - name: Git config user.name
      community.general.git_config:
        name: user.name
        scope: global
        value: "Alexey Donov"

    - name: Git config user.email
      community.general.git_config:
        name: user.email
        scope: global
        value: "alexeydonov@mac.com"
